// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgBwXpYlefxWamFTyej4Bx42GLHV6kW8M',
    appId: '1:541649249243:web:084c1196786b37baa17dfe',
    messagingSenderId: '541649249243',
    projectId: 'miniproject-posyanducare',
    authDomain: 'miniproject-posyanducare.firebaseapp.com',
    storageBucket: 'miniproject-posyanducare.appspot.com',
    measurementId: 'G-6RDPCTX9WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD158Y8Bq53dMg5D4edUVtXqHeE2jOmI7A',
    appId: '1:541649249243:android:70706eb2b825ad2aa17dfe',
    messagingSenderId: '541649249243',
    projectId: 'miniproject-posyanducare',
    storageBucket: 'miniproject-posyanducare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAg10Q6ycrAFqPp71VCwBUFrsOfGdwblI',
    appId: '1:541649249243:ios:b91f8a8c45213819a17dfe',
    messagingSenderId: '541649249243',
    projectId: 'miniproject-posyanducare',
    storageBucket: 'miniproject-posyanducare.appspot.com',
    iosClientId: '541649249243-rar39i3bljlkphcb6gg1sghq398un0ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.posyanduCareApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAg10Q6ycrAFqPp71VCwBUFrsOfGdwblI',
    appId: '1:541649249243:ios:b91f8a8c45213819a17dfe',
    messagingSenderId: '541649249243',
    projectId: 'miniproject-posyanducare',
    storageBucket: 'miniproject-posyanducare.appspot.com',
    iosClientId: '541649249243-rar39i3bljlkphcb6gg1sghq398un0ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.posyanduCareApps',
  );
}
